services:
  - type: web
    name: stress-detection-api
    env: docker
    repo: https://github.com/cracery/SLD_server_main
    branch: main
    envVars:
      - key: MODEL_BASE_URL
        value: "1-ZfjNWADgAOxA2up5ddiiihmt4keB6Kv"
    healthCheckPath: /healthcheck
    autoDeploy: true
